### ISSUE TITLE
test.cpp is missing

### ISSUE THREAD

**Issue by papipopapu** [usnistgov/multicomplex#2]
It is still added in CMakeLists

**Comment by ianhbell** [comment]
Where do you see it referenced?

**Comment by papipopapu** [comment]
My bad, I cloned the repo from niahbell/multicomplex, which adds test.cpp as executable in CMakeLists. I mindlessly followed the README, which shows an example install from that repo.

**Comment by ianhbell** [comment]
Please close the issue then

**Comment by papipopapu** [comment]
Np
